name: GitHub Actions Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: |
          cd client/
          npm install
          npm run build

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with: # shimataro/ssh-key-actionに渡すパラメーター
          key: ${{ secrets.SSH_KEY }} # 必須
          name: id_rsa # 省略可
          known_hosts: ${{ secrets.KNOWN_HOSTS }} # 必須

      - name: run deploy script
        run: |
          ls 
          bash ./deploy.sh
