name: GitHub Actions Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: |
          cd client/
          npm install
          npm run build 
          bash ../deploy.sh

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1

      - name: run deploy script
        run: ls
